---
name: GitHub Pages

on:
  push:
    # branches: ["dev", "dev-update"]
    branches: ["NEVER"]
  workflow_dispatch: # Allows you to run this workflow manually from the Actions tab

jobs:
  Pages:
    uses: dennykorsukewitz/dennykorsukewitz/.github/workflows/reusable.pages.yml@dev
    secrets:
      PAT: ${{ secrets.PAT }}
